name: taches_a_faire_main
description: Une application de To-Do List gamifiÃ©e construite en Flutter.
# Le numÃ©ro de version est important pour le dÃ©ploiement.
version: 1.0.0+1 

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ðŸ”‘ NOUVEAU: 1. DÃ©pendance pour l'internationalisation
  flutter_localizations: 
    sdk: flutter         
  # ------------------------------------------------
  
  provider: ^6.0.5 
  uuid: ^4.4.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # ðŸ”‘ NOUVEAU: 2. Indique Ã  Flutter de gÃ©nÃ©rer le code de localisation
  generate: true 
  # --------------------------------------------------

  # assets:
  #   - images/a_dot_burr.jpeg
